### ISSUE TITLE
I have a little problem

### ISSUE THREAD

**Issue by julienchrist** [ddvk/ddvk#1]
Since the installation of einkpads Template and since the istallation of Update 2.6 i can't re install the ddvk hack on my rmearkable 2.

When i open "terminal" on my mac and when i put ssh root@ etc.. i can't go further.

I have this message :

WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

And i can't install the wonderful Ddvk hack :.(

**Comment by ddvk** [comment]
run: rm ~/.ssh/known_hosts

**Comment by julienchrist** [comment]
Thank you so much for your project !!!
